import React from "react";
import { MyREST } from "./TypeWareScraping";
import { RestWareDataToPersion } from "../../../../function/RestWareDataToPersion";
interface Props {
  data: MyREST;
}
export const InfoWare: React.FC<Props> = ({ data }) => {
  return (
    <div className="container-infoware">
      {data && (
        <>
          {Object.entries(data.allInfo.resData.initialIranCodeInfo).map(
            (value, index) => (
              <div
                key={"initialIranCodeInfo" + index}
                className="field-InfoWare"
              >
                <p className="title-InfoWare">{value[0]} : </p>
                <p className="text-InfoWare">
                  {value[1] === "" ? "وجود ندارد" : value[1]}
                </p>
              </div>
            )
          )}
          {Object.entries(data.allInfo.supplyData).map(
            (value, index) =>
              value[0] !== "products" &&
              (value[0] === "contactInfo" ? (
                Object.entries(data.allInfo.supplyData.contactInfo).map(val => (
                  <div
                    key={"contactInfo" + index}
                    className="field-InfoWare"
                    style={{ display: "flex" }}
                  >
                    <p className="title-InfoWare">
                      {RestWareDataToPersion(val[0])} :{" "}
                    </p>
                    <p className="text-InfoWare">
                      {val[1] === "" ? "وجود ندارد" : val[1]}
                    </p>
                  </div>
                ))
              ) : (
                <div key={"supplyData" + index} className="field-InfoWare">
                  <p className="title-InfoWare">
                    {RestWareDataToPersion(value[0])} :{" "}
                  </p>
                  <p className="text-InfoWare">
                    {value[1] === "" ? "وجود ندارد" : value[1]}
                  </p>
                </div>
              ))
          )}
          {Object.entries(data.allInfo.catalog).map((value, index) =>
            value[0] === "productDetailsTable" ? (
              Object.entries(data.allInfo.catalog.productDetailsTable).map(
                val =>
                  val[0] !== "internationalCondes" && (
                    <div
                      key={"productDetailsTable" + index}
                      className="field-InfoWare"
                    >
                      <p className="title-InfoWare">
                        {RestWareDataToPersion(val[0])} :{" "}
                      </p>
                      <p className="text-InfoWare">
                        {val[1] === "" ? "وجود ندارد" : val[1]}
                      </p>
                    </div>
                  )
              )
            ) : value[0] === "merchandiseSpecs" ? (
              Object.entries(data.allInfo.catalog.merchandiseSpecs).map(val => (
                <div
                  key={"merchandiseSpecs" + index}
                  className="field-InfoWare"
                >
                  <p className="title-InfoWare">
                    {RestWareDataToPersion(val[0])} :{" "}
                  </p>
                  <p className="text-InfoWare">
                    {val[1] === "" ? "وجود ندارد" : val[1]}
                  </p>
                </div>
              ))
            ) : (
              <div key={"catalog" + index} className="field-InfoWare">
                <p className="title-InfoWare">
                  {RestWareDataToPersion(value[0])} :{" "}
                </p>
                <p className="text-InfoWare">
                  {value[1] === "" ? "وجود ندارد" : value[1]}
                </p>
              </div>
            )
          )}
        </>
      )}
    </div>
  );
};

// Generated by https://quicktype.io
